server:
  port: ${nimble.server.port}

eureka:
  instance:
    hostname: ${nimble.eureka.instance.hostname}
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
    use-read-only-response-cache: false
  client:
    registerWithEureka: ${nimble.eureka.client.registerWithEureka}
    fetchRegistry:  ${nimble.eureka.client.fetchRegistry}
    serviceUrl:
      defaultZone: ${nimble.eureka.client.serviceUrl.defaultZone}

logging:
  level:
    root: ${nimble.logging.level.root}
    com.nimble.eureka: ${nimble.logging.level.com.nimble.eureka}
