nimble:
  server:
    port: 7902

  spring:
    application:
      name: eureka

  eureka:
    instance:
      appname: ${nimble.spring.application.name}
      hostname: eureka2
      instance-id: ${spring.application.name}:${server.port}
      preferIpAddress: false
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://${nimble.otherEurekaServer.hostname}:${nimble.otherEurekaServer.port}/eureka/

  logging:
    level:
      root: info
      com.nimble.eureka: debug

  otherEurekaServer:
    hostname: eureka1
    port: 7901